# Generated by Django 4.2.3 on 2023-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('departamento', models.DateField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
        ),
    ]
