# Generated by Django 4.2.3 on 2023-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='departamento',
            field=models.CharField(max_length=15),
        ),
    ]
